optimize: optimize/images optimize/videos optimize/css optimize/js

optimize/images:
	@echo "Images optimized!"

optimize/videos:
	@echo "Videos optimized!"

optimize/css:
	@echo "CSS optimized!"

optimize/js:
	@echo "JS optimized!"
