# 👇 This is a rule 👇
# target: dependency-1 dependency-2
# (tab) 	shell lines
# 👆 This is a rule 👆

deploy: build
	@echo "🚀 Deploy!!!"

build: lint test
	@echo "📦 Build done"

lint:
	@echo "🔦 Code linted\n" \
	      "  --- Level supreme"

test:
	@echo "🏃‍ Running tests"
	@echo "   ✅  All tests passed"


# the-test:
#	@echo "Codely"
