deploy: build
	@echo "🚀 Deploy!!!"

build: lint test
	@echo "📦 Build done"

test:
	@echo "🏃‍ Running tests"
	@echo "   ✅  All tests passed"

lint:
	@echo "🔦 Code linted\n" \
	      "  --- Level supreme"

# the-test:
#	@echo "Codely"
