.DEFAULT_GOAL := deploy

build: lint test
	@echo "📦 Build done"

test:
	@echo "🏃‍ Running tests"
	@echo "   ✅  All tests passed"

lint:
	@echo "🔦 Code linted\n" \
	      "  --- Level supreme"

deploy: build
	@echo "🚀 Deploy!!!"
